For NOAA, added a vaildation step to check if the required env variables are there before build and sync

diff --git a/.github/workflows/deploy-noaa.yml b/.github/workflows/deploy-noaa.yml
--- a/.github/workflows/deploy-noaa.yml
+++ b/.github/workflows/deploy-noaa.yml
@@ -48,6 +48,25 @@ jobs:
       - name: Install Yarn
         run: npm install -g yarn
 
+
+      - name: Validate required variables and secrets
+        run: |
+          missing_vars=()
+
+          # Check for required variables
+          [ -z "${{ vars.PUBLIC_URL_NOAA }}" ] && missing_vars+=("vars.PUBLIC_URL_NOAA")
+          [ -z "${{ secrets.MAP_ACCESS_TOKEN }}" ] && missing_vars+=("secrets.MAP_ACCESS_TOKEN")
+          [ -z "${{ secrets.DEPLOYMENT_ROLE_ARN }}" ] && missing_vars+=("secrets.DEPLOYMENT_ROLE_ARN")
+          [ -z "${{ secrets.CF_DISTRIBUTION_ID }}" ] && missing_vars+=("secrets.CF_DISTRIBUTION_ID")
+
+          # If any variables are missing, print them and exit with an error
+          if [ ${#missing_vars[@]} -ne 0 ]; then
+            echo "Error: The following required variables are missing:"
+            printf '%s\n' "${missing_vars[@]}"
+            exit 1
+          fi
+        shell: bash
+
       - name: Build for production 🔧
         working-directory: ./noaa-cpfp-point
         run: |
